baseurl: https://bryantchen.netlify.com/
builddrafts: no
canonifyurls: no
languageCode: en-US
contentdir: content
layoutdir: layouts
publishdir: public
math: true
author: Bryant Chen
title: Bryant Chen
theme: hugo-goa
disqusShortname: https-shenoybr-github-io-hugo-goa-demo
googleAnalytics: XYZ
enableRobotsTXT: yes
params:
  author: Bryant Chen
  authorimage: "profile 4.jpg"
  dateformat: Jan 2, 2006
  description: This website is for sharing my personal thoughts and professional work in statistics.
  extra:
    copyright: © 2021. Bryant Chen. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/).
    displayrssicon: yes
    highlightjs: yes
    poweredby: yes
    socialmarkup: yes
    toc: yes
  intro: Statistician/Data Scientist
  meta:
    description: Simple minimalist theme
    keywords: minimalist,blog,goa,hugo,developer
  social:
    email: bryantch@buffalo.edu
    github: bryantch
    instagram: bryantch93
    linkedin: bryantch
    strava: 4981709
    
menu:
  main:
    - identifier: professional
      name: professional
      url: /professional/
      weight: 100
    - identifier: personal
      name: personal
      url: /Resume_Bryant Chen.pdf
      weight: 200
    - identifier: about
      name: about
      url: /about/
      weight: 300
    - identifier: resume
      name: resume
      url: /Resume_Bryant Chen.pdf
      weight: 400

markup:
  goldmark:
    renderer:
      unsafe: true
