---
title: "2022 Salt Lake City Marathon"
author: "Bryant Chen"
date: 2022-04-29
categories: ["Blog"]
tags: ["Simulation", "Bayesian", "Hierarchical","MCMC"]
description: A statistical analysis of the 2022 Salt Lake City Marathon.
output:
  html_document: default
  pdf_document: default
---

**Introduction**

I recently ran the half marathon segment of the annual Salt Lake City Marathon and after all of the post-race exhaustion, runner's high and celebration with friends had died down, I was curious about how I did relative to everyone else who ran. After all, it only takes a sudden thought to start comparing and feeling self-conscious. I wondered how the distribution of completion and pace times looked like plus how that looked like for different age groups since those metrics were provided for each runner on the results page. Even though you are given your place out of those who ran, I wanted to see if I can visualize that and if I can model these given the data to do a prediction for next year's race. Moreover, I wanted to generalize this approach to other years where not only were these metrics available for but also where the following year's metrics were available too so I can see how my predictions did against actual results. Nobody has time to wait another whole year! For me, this was more of an exercise on getting my hands on the data via API's from the site that the results are hosted on so I've documented that process below. Once I got the data, I described some of the descriptive results that I got with it before talking about the model I constructed. ~Spoiler~ I applied a Bayesian Hierarchical Model!

**Getting the Data**

To get the data for the race onto my computer, 

download 




